### PR TITLE
Create `v1.4` subfolder in `versioned_docs` folder & modify config files

### PR DESCRIPTION
**Pull request by jillian-maroket**
Change log:
- Created `version-v1.4` subfolder in `versioned_docs` folder (identical copy of `docs` folder)
- Updated`docusaurus.config.js` (v1.5 dev and v1.4 latest)
- Updated `versions.json` (v1.4) 
- Updated `README.md` (not sure if necessary but it contains version info)

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Review by tserong — COMMENTED** [review]
The content is fine (of course!) but there's something weird going on when I preview this, or run it via `yarn start` locally -- it still defaults to showing the v1.3 docs, and when I switch to view v1.4, the sidebar/menu is missing.

**Comment by jillian-maroket** [comment]
@tserong Thanks for catching that. I may need to add a file.

**Comment by jillian-maroket** [comment]
@tserong The v1.4 doc now has a sidebar, but the preview still defaults to v1.3. If fine with you, we can merge the changes now and I'll just open another PR when I figure out that other issue.

**Review by bk201 — APPROVED** [review]
Thanks!

**Review by tserong — APPROVED** [review]
Sidebar LGTM in the preview.

I found one other thing, when running `yarn start` with the latest change applied, is that it complains:

```
[INFO] Starting the development server...
[ERROR] Loading of version failed for version v1.4
[ERROR] Error: Invalid sidebar file at "versioned_sidebars/version-v1.4-sidebars.json".
These sidebar document ids do not exist:
- api/create-namespaced-cluster-network
- api/create-namespaced-key-pair
- api/create-namespaced-network-attachment-definition
- api/create-namespaced-node-network
- api/create-namespaced-persistent-volume-claim
- api/create-namespaced-support-bundle
- api/create-namespaced-upgrade
- api/create-namespaced-virtual-machine
- api/create-namespaced-virtual-machine-backup
- api/create-namespaced-virtual-machine-image
- api/create-namespaced-virtual-machine-instance-migration
- api/create-namespaced-virtual-machine-restore
- api/create-namespaced-virtual-machine-template
- api/create-namespaced-virtual-machine-template-version
- api/delete-namespaced-cluster-network
- api/delete-namespaced-key-pair
- api/delete-namespaced-network-attachment-definition
- api/delete-namespaced-node-network
- api/delete-namespaced-persistent-volume-claim
- api/delete-namespaced-support-bundle
- api/delete-namespaced-upgrade
- api/delete-namespaced-virtual-machine
- api/delete-namespaced-virtual-machine-backup
- api/delete-namespaced-virtual-machine-image
- api/delete-namespaced-virtual-machine-instance-migration
- api/delete-namespaced-virtual-machine-restore
- api/delete-namespaced-virtual-machine-template
- api/delete-namespaced-virtual-machine-template-version
- api/harvester-apis
- api/list-key-pair-for-all-namespaces
- api/list-namespaced-cluster-network
- api/list-namespaced-key-pair
- api/list-namespaced-network-attachment-definition
- api/list-namespaced-node-network
- api/list-namespaced-persistent-volume-claim
- api/list-namespaced-support-bundle
- api/list-namespaced-upgrade
- api/list-namespaced-virtual-machine
- api/list-namespaced-virtual-machine-backup
- api/list-namespaced-virtual-machine-image
- api/list-namespaced-virtual-machine-instance
- api/list-namespaced-virtual-machine-instance-migration
- api/list-namespaced-virtual-machine-restore
- api/list-namespaced-virtual-machine-template
- api/list-namespaced-virtual-machine-template-version
- api/list-network-attachment-definition-for-all-namespaces
- api/list-persistent-volume-claim-for-all-namespaces
- api/list-support-bundle-for-all-namespaces
- api/list-upgrade-for-all-namespaces
- api/list-virtual-machine-backup-for-all-namespaces
- api/list-virtual-machine-for-all-namespaces
- api/list-virtual-machine-image-for-all-namespaces
- api/list-virtual-machine-instance-for-all-namespaces
- api/list-virtual-machine-instance-migration-for-all-namespaces
- api/list-virtual-machine-restore-for-all-namespaces
- api/list-virtual-machine-template-for-all-namespaces
- api/list-virtual-machine-template-version-for-all-namespaces
- api/patch-namespaced-cluster-network
- api/patch-namespaced-key-pair
- api/patch-namespaced-network-attachment-definition
- api/patch-namespaced-node-network
- api/patch-namespaced-persistent-volume-claim
- api/patch-namespaced-support-bundle
- api/patch-namespaced-upgrade
- api/patch-namespaced-virtual-machine
- api/patch-namespaced-virtual-machine-backup
- api/patch-namespaced-virtual-machine-image
- api/patch-namespaced-virtual-machine-instance-migration
- api/patch-namespaced-virtual-machine-restore
- api/patch-namespaced-virtual-machine-template
- api/patch-namespaced-virtual-machine-template-version
- api/read-namespaced-cluster-network
- api/read-namespaced-key-pair
- api/read-namespaced-network-attachment-definition
- api/read-namespaced-node-network
- api/read-namespaced-persistent-volume-claim
- api/read-namespaced-support-bundle
- api/read-namespaced-upgrade
- api/read-namespaced-virtual-machine
- api/read-namespaced-virtual-machine-backup
- api/read-namespaced-virtual-machine-image
- api/read-namespaced-virtual-machine-instance
- api/read-namespaced-virtual-machine-instance-migration
- api/read-namespaced-virtual-machine-restore
- api/read-namespaced-virtual-machine-template
- api/read-namespaced-virtual-machine-template-version
- api/replace-namespaced-cluster-network
- api/replace-namespaced-key-pair
- api/replace-namespaced-network-attachment-definition
- api/replace-namespaced-node-network
- api/replace-namespaced-persistent-volume-claim
- api/replace-namespaced-support-bundle
- api/replace-namespaced-upgrade
- api/replace-namespaced-virtual-machine
- api/replace-namespaced-virtual-machine-backup
- api/replace-namespaced-virtual-machine-image
- api/replace-namespaced-virtual-machine-instance-migration
- api/replace-namespaced-virtual-machine-restore
- api/replace-namespaced-virtual-machine-template
- api/replace-namespaced-virtual-machine-template-version
```

I'm not sure how the api docs work, I know @m-ildefons did some work on that previously so possibly he can advise? But anyway I'm fine to merge this as-is and fix the remaining issues separately if that work for everyone.

**Comment by tserong** [comment]
That's better, in that the error list is a _lot_ shorter:

```
[INFO] Starting the development server...
[ERROR] Loading of version failed for version v1.4
[ERROR] Error: Invalid sidebar file at "versioned_sidebars/version-v1.4-sidebars.json".
These sidebar document ids do not exist:
- api/create-namespaced-cluster-network
- api/create-namespaced-node-network
- api/delete-namespaced-cluster-network
- api/delete-namespaced-node-network
- api/list-namespaced-cluster-network
- api/list-namespaced-node-network
- api/patch-namespaced-cluster-network
- api/patch-namespaced-node-network
- api/read-namespaced-cluster-network
- api/read-namespaced-node-network
- api/replace-namespaced-cluster-network
- api/replace-namespaced-node-network
```

...but I haven't figured out how to fix those :-/

**Pull request merged**
