### PR TITLE
Put version v1.1 to history and add dev version

### PR DESCRIPTION
**Pull request by vickyhella**
- Adds the dev version
- Puts v1.1 to versioned_docs and edits relevant files, such as the sidebar
- Creates a `dev` folder to store images for the dev version, and also edits the img paths in dev docs

### CODE REVIEW

**Review by btat — APPROVED** [review]
LGTM

**Comment by vickyhella** [comment]
> can we change the label to `v1.1-dev`, everything else is LGTM, thanks. image

Already updated. Thanks!

**Comment by vickyhella** [comment]
Already resolved the conflicts and updated the PR based on the latest `main` branch. 

BTW, it's recommended that we don't merge other PRs before this one gets merged (if possible). Otherwise, there will be a lot of conflicts as the doc locations are totally changed.

One more thing, Kiefer was wondering if the `v1.1-dev` label should be `v1.2-dev`. @guangbochen would you please take a second look? Thanks!

CC @bk201

**Comment by guangbochen** [comment]
@vickyhella after offline discussion, we think it can be renamed to `v1.2-dev`, so for new doc PRs:
- submit both `v1.1.2` and `v1.2` related doc PRs to the `/docs` path first.
- for the `v1.1.2-dev` doc PR, please use an independent commit with a meaningful title starting with `[v1.1.2 -  *]`, therefore, it can be backported to the v1.1 path later easier.

**Comment by vickyhella** [comment]
> @vickyhella after offline discussion, we think it can be renamed to `v1.2-dev`, so for new doc PRs:
> 
> * submit both `v1.1.2` and `v1.2` related doc PRs to the `/docs` path first.
> * for the `v1.1.2-dev` doc PR, please use an independent commit with a meaningful title starting with `[v1.1.2 -  *]`, therefore, it can be backported to the v1.1 path later easier.

OK. Since now we know the `docs` path will be used for v1.2, I will also change the img path from `/img/dev` to `/img/v1.2`.

**Comment by vickyhella** [comment]
@guangbochen Already updated the version label and the img paths:
- Label for the `docs` folder is now `v1.2-dev`
- img paths for the `docs` folder is now `/img/v1.2`

**Review by guangbochen — APPROVED** [review]
LGTM and please squash the commits for merge, thanks.

**Comment by vickyhella** [comment]
> LGTM and please squash the commits for merge, thanks.

Already squashed the latest few commits. Previous ones cannot be squashed as the `main` branch was merged when resolving the conflicts.

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
