### PR TITLE
Migrate to Docusaurus

### PR DESCRIPTION
**Pull request by vickyhella**
- Migrates the doc framework to Docusaurus (using the latest v2.1.0)
- Updates formats according to Docusaurus requirements
- Adds GitHub Actions for deploying to GitHub Pages
- Adds versioning (v1.0 and v0.3) and i18n settings, and adds Chinese docs
- Moves v1.0 images to `/static/img/` so that Chinese docs can easily reuse these images

### CODE REVIEW

**Comment by guangbochen** [comment]
@vickyhella thanks for adding the PR and we should be able to finish the review soon, can u please help to add a new version of `v1.1-dev` so we can have a dest branch to engineer to submit the new doc for the upcoming v1.1 release? thanks.

**Comment by vickyhella** [comment]
@guangbochen Already added the settings for dev-docs:
- v1.1 docs are located in `/docs`, and the URL will be docs.harvesterhci.io/next
- v1.0 docs are located in `/versioned_docs/version-v1.0`, and the URL will be docs.harvesterhci.io/
- Image paths are separated for these two versions for easier maintenance, which are now in `/static/img/v1.0` and `/static/img/v1.1`

**Review by bk201 — APPROVED** [review]
Thanks for the hard work!

**Comment by vickyhella** [comment]
Already updated per comments.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
