### PR TITLE
feat(cloud-provider): add single node known issue

### PR DESCRIPTION
**Pull request by FrankYang0529**
issue: https://github.com/harvester/harvester/issues/6799

### CODE REVIEW

**Review by bk201 — APPROVED** [review]

**Review by starbops — APPROVED** [review]
LGTM, thanks.

**Comment by jillian-maroket** [comment]
@asettle The new content is for Prime customers. How do you want to handle this?

**Comment by asettle** [comment]
> @asettle The new content is for Prime customers. How do you want to handle this?

This release note should only go into prime docs. As a community user, you shouldn't be worried about upgrading from community to Prime. However, Prime users will be as they are already looking to purchase and migrate from Prime. This should be kept separate and what we want to be saying is, "When upgrading your Rancher version from the community version to the SUSE supported Prime version, the harvester-cloud-provider pod won't be ready in a single-node cluster."

**Comment by FrankYang0529** [comment]
Hi @jillian-maroket, the content LGTM. Thanks for updating it 👍 .

**Comment by innobead** [comment]
Do we still need this PR? since it has been added to the prime doc, https://github.com/rancher/prime-docs/pull/23.

**Comment by FrankYang0529** [comment]
> Do we still need this PR? since it has been added to the prime doc, [rancher/prime-docs#23](https://github.com/rancher/prime-docs/pull/23).

I think we can close this one. Thanks for the reminder.

**Pull request closed without merging**
