### PR TITLE
Enable analytics

### PR DESCRIPTION
**Pull request by btat**
This PR enables Google Analytics through [Google Tag Manager](https://marketingplatform.google.com/about/tag-manager/) as part of an effort by the Docs team to better understand how users use our docs. 

Please connect with @gunamata for details and access to data/dashboards when available.

Note that Docusaurus is bumped to v2.3.1 in order to use the `plugin-google-tag-manager` plugin that becomes available as part of the [presets](https://docusaurus.io/docs/using-plugins#using-presets).

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
LGTM

**Review by vickyhella — APPROVED** [review]
LGTM

**Review by LucasSaintarbor — APPROVED** [review]
+1 LGTM 👍

**Comment by guangbochen** [comment]
The bumped version `v2.3.1`  will have contains some conflict with a required version for the [swagger-api doc plugin support](https://github.com/harvester/docs/pull/242/files), can we PTAL if the v2.2.0 version works for the analytics, thanks.

**Comment by btat** [comment]
> The bumped version `v2.3.1` will contains some conflict with a required version of the [swagger-api doc plugin support](https://github.com/harvester/docs/pull/242/files), can we PTAL if the v2.2.0 version works for the analytics, thanks.

Hi @guangbochen, there is a third party plugin that we've previously used with Docusaurus v2.2.0 on the Rancher Manager docs, but that plugin has been unmaintained since 2020 which is why we moved to this plugin bundled with Docusuarus v2.3.1 when it became available.

Are there plans to use a more recent version of the API plugin for PR #242 before it's merged? If so, then 
based on this [comment](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/323#issuecomment-1468571368) (from one of contributors of the API plugin) bumping to version `2.0.0-beta` of the plugin will support Docusaurus v2.3.1. That would avoid the conflicts.

**Comment by vickyhella** [comment]
@btat Thanks for the info! I bumped the openapi plugin to the new `2.0.0-beta.1` version and Docusaurus to `v.2.3.1`, and they work well together (no more crashed pages). 
CC @guangbochen I think this PR can be safely merged. I will rebase https://github.com/harvester/docs/pull/242 and bump the plugin versions when this PR is merged.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
