### PR TITLE
Add terraform support matrix

### PR DESCRIPTION
**Pull request by futuretea**
Signed-off-by: futuretea <Hang.Yu@suse.com>

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Comment by bk201** [comment]
Do we also need to tag v1.1.0-harvester in https://github.com/harvester/terraformer/tags ?

**Comment by futuretea** [comment]
> Do we also need to tag v1.1.0-harvester in https://github.com/harvester/terraformer/tags ?

https://github.com/harvester/terraformer/actions/runs/3319373997/jobs/5484452555 release action is running

**Comment by futuretea** [comment]
https://github.com/harvester/terraformer/releases/tag/v1.1.0-harvester released

**Pull request merged**
