### PR TITLE
Add multi CSI support summary and csi-driver-config setting

### PR DESCRIPTION
**Pull request by LucasSaintarbor**
References https://github.com/harvester/harvester/issues/2405, https://github.com/harvester/harvester/pull/3666

Documents multi CSI support on StorageClass page and explains how to edit the new `csi-driver-config` setting

### CODE REVIEW

**Review by futuretea — APPROVED** [review]
LGTM, thanks. Just need to squash commits

**Review by lanfon72 — COMMENTED** [review]
#3666 also introduce:
- Add a new option `os.persistent_state_paths` to the Harvester OS configuration.
- Add a new option `os.after_install_chroot_commands` to the Harvester OS configuration.

Both would need to add into `install/harvester-configuration.md`

**Comment by LucasSaintarbor** [comment]
> [#3666](https://github.com/harvester/harvester/pull/3666) also introduce:
> 
> * Add a new option `os.persistent_state_paths` to the Harvester OS configuration.
> * Add a new option `os.after_install_chroot_commands` to the Harvester OS configuration.
> 
> Both would need to add into `install/harvester-configuration.md`

@lanfon72 I added `os.persistent_state_paths` and `os.after_install_chroot_commands` to `install/harvester-configuration.md`. Not sure where to add these to the new options in ## Configuration Example, may you update the config example + review to the definition and example for each option? Thanks!

**Comment by lanfon72** [comment]
Thank you @LucasSaintarbor, it looks good enough for me. :smile_cat:  I think it should be fine to not update the content of `Configuration Example`, both configure options are optional.

For `os.after_install_chroot_commands`, was tested in [#harvester/3689](https://github.com/harvester/harvester/issues/3689), and there have a caveat that the `nameserver` might not available, so user would need to update `/etc/resolv.conf` manually while using the configure option to install package with URL. [^1]

[^1]: https://github.com/harvester/harvester/issues/3689#issuecomment-1563130124

**Comment by futuretea** [comment]
@LucasSaintarbor  Thanks! This note https://github.com/harvester/harvester/blob/master/enhancements/20230316-multi-csi-support.md?plain=1#L137 also need to be included.

**Comment by LucasSaintarbor** [comment]
@futuretea Added the note you referenced for making changes persistent across an upgrade (https://github.com/harvester/docs/pull/372#issuecomment-1665594895)

@lanfon72 Added info and example about accessing a domain name to install package using an URL (https://github.com/harvester/docs/pull/372#issuecomment-1662026401) 

PTAL, thanks!

**Review by lanfon72 — APPROVED** [review]
LGTM, thanks

**Comment by jeff-radick-suse** [comment]
I've modified the content and pushed a few commits.  There was some description of the procedure that was clumsy and which is now simplified, and some important stuff that was missing.  I tried to follow the formatting changes but I'm not sure I have it right. At any rate the _semantic_ content is complete as far as I can tell, as long as no reviewers find errors.

**Pull request merged**
