### PR TITLE
update the description of server_url

### PR DESCRIPTION
**Pull request by w13915984028**
update the description of server_url
Signed-off-by: Jian Wang <w13915984028@gmail.com>

issue: https://github.com/harvester/harvester/issues/2930

### CODE REVIEW

**Review by vickyhella — APPROVED** [review]
LGTM and thanks!

**Review by guangbochen — COMMENTED** [review]
LGTM, @w13915984028  can we also backport this to the [v1.0 path](https://github.com/harvester/docs/tree/main/versioned_docs/version-v1.0), thanks.

**Comment by w13915984028** [comment]
> LGTM, @w13915984028 can we also backport this to the [v1.0 path](https://github.com/harvester/docs/tree/main/versioned_docs/version-v1.0), thanks.

@guangbochen v1.0 is also updated in this PR, please re-check, thanks.

**Review by guangbochen — APPROVED** [review]
thanks for the changes.

**Pull request merged**
