### PR TITLE
[v1.1.2] add harvester-system into noProxy

### PR DESCRIPTION
**Pull request by starbops**
Signed-off-by: Zespre Chang <zespre.chang@suse.com>

Related issue: harvester/harvester#2782

Depend on PR: harvester/harvester#2808

### CODE REVIEW

**Review by futuretea — APPROVED** [review]
LGTM.Thanks!

**Review by vickyhella — APPROVED** [review]
LGTM!

**Comment by LucasSaintarbor** [comment]
@guangbochen Following up to see if this change is valid? Thanks!

**Review by guangbochen — COMMENTED** [review]
The change is valid, please help to backport to the [versioned v1.1 path](https://github.com/harvester/docs/tree/main/versioned_docs/version-v1.1) since the PR is introduced via v1.1.2.
Additionally, can we add a note that `harvester-system` is added via the `v1.1.2` version, thanks.

**Comment by starbops** [comment]
Hi @guangbochen, I have updated the changes. Would you please take a look? Thanks!

**Review by guangbochen — APPROVED** [review]
LGTM, and will merge before the v1.1.2 release, thanks.

**Pull request merged**
