### PR TITLE
Add v1.1.2 upgrade documents

### PR DESCRIPTION
**Pull request by bk201**

### CODE REVIEW

**Review by vickyhella — COMMENTED** [review]
Just some small suggestions ^^
I only added comments for docs in `/docs`. Please also bring the changes to other docs in `versioned_docs` and `i18n`. Thanks!

**Comment by bk201** [comment]
Thanks, @vickyhella. I accept all suggestions!

**Review by vickyhella — APPROVED** [review]

**Review by Vicente-Cheng — APPROVED** [review]
LGTM!

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
